### ISSUE TITLE
Feature: add release_version template variable

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [apexskier/github-release-commenter#432]
I'd like to use a `comment-template` that links to the npm package. But right now, there's no way to comment a link like `.../v/1.2.3`. `{release_tag}` itself contains a `v`.

Could we also have a template variable like `release_version`, that's the same as `release_tag` but without prefixes such as `v`?

Reference: https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues/427

I'll note that one workaround is to manually put the version in a GitHub environment variable:

```yml
      - run: echo "npm_version=$(npm pkg get version | tr -d '"')" >> "$GITHUB_ENV"
      - uses: apexskier/github-release-commenter@v1
        with:
          comment-template: |
            npm link: https://www.npmjs.com/package/your-package/v/${{ env.npm_version }}) 
```
