### ISSUE TITLE
Doesnt work when release created by action

### ISSUE THREAD

**Issue by SamuelJohnsonMedia** [apexskier/github-release-commenter#9]
I am using the `actions/create-release` action to create my release yet this is not triggering your action for some reason. Is this expected?

I have tried the `published` and `released` types:

```
name: Releases

on:
  release:
    types: [released]

jobs:
  release:
    steps:
      - uses: apexskier/github-release-commenter@latest
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

And my build pipeline action for creating the release:
```
      - name: Create Release
        uses: actions/create-release@v1
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.gitversion.outputs.SemVer }}
          release_name: Release v${{ steps.gitversion.outputs.SemVer }}
          body: ${{ steps.changelog.outputs.changelog }}
```
